### PR TITLE
Fix sync remote

### LINKED ISSUE #401: [BUG] Anonymous group, Thredds config page, not working after upgrade from 1.7.3 to 3.5.1
**Describe the bug**
Going here https://lvupavics.ouranos.ca/magpie/ui/groups/anonymous/thredds

Result in this page: 
Screenshot_2021-03-25 Magpie-lvupavics-group-anon-thredds

With the following error in `docker logs magpie`.

```
[2021-03-25 15:02:18,563] INFO       [ThreadPoolExecutor-0_0][magpie.utils] Request: [GET lvupavics.ouranos.ca:443 /magpie/services/thredds/resources]
[2021-03-25 15:02:18,826] ERROR      [ThreadPoolExecutor-0_0][magpie.ui.utils] Unexpected API error under UI operation. [AttributeError: 'result' object has no attribute 'Resource']
Traceback (most recent call last):
  File "/opt/local/src/magpie/magpie/ui/utils.py", line 121, in wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/opt/local/src/magpie/magpie/ui/management/views.py", line 751, in edit_group
    info = self.get_remote_resources_info(res_perms, services, session)
  File "/opt/local/src/magpie/magpie/ui/management/views.py", line 808, in get_remote_resources_info
    res_perms = self.merge_remote_resources(res_perms, services, session)
  File "/opt/local/src/magpie/magpie/ui/management/views.py", line 823, in merge_remote_resources
    resources_for_service = merge(res_perms, service_values["service_sync_type"], service_id, session)
  File "/opt/local/src/magpie/magpie/cli/sync_resources.py", line 51, in merge_local_and_remote_resources
    remote_resources = _query_remote_resources_in_database(service_id, session=session)
  File "/opt/local/src/magpie/magpie/cli/sync_resources.py", line 244, in _query_remote_resources_in_database
    tree = get_resource_children(main_resource, session, models.REMOTE_RESOURCE_TREE_SERVICE)
  File "/opt/local/src/magpie/magpie/api/management/resource/resource_utils.py", line 196, in get_resource_children
    tree_struct_dict = tree_service_builder.build_subtree_strut(query)
  File "/usr/local/lib/python3.7/site-packages/ziggurat_foundations/models/services/resource_tree.py", line 76, in build_subtree_strut
    return self.service.build_subtree_strut(result=result, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ziggurat_foundations/models/services/resource_tree_postgres.py", line 152, in build_subtree_strut
    new_elem = {"node": node.Resource, "children": OrderedDict()}
AttributeError: 'result' object has no attribute 'Resource'
[2021-03-25 15:02:18,839] INFO       [ThreadPoolExecutor-0_0][magpie.utils] Request: [POST lvupavics.ouranos.ca:443 /magpie/ui/error]
```

Note that the Jenkins test suite actually passed on that instance after the upgrade: https://daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/master/239/console

Also when the magpie container was recreated at the moment of the upgrade, there was no error related to DB migration.

**To Reproduce**
My dev server autodeployed the PR https://github.com/bird-house/birdhouse-deploy/pull/107

**Expected behavior**
Being able to see the permissions for Thredds for the anonymous group.

### PR DESCRIPTION
**Pull request by fmigneault**
- adds a loading animation to have UI feedback on sync in progress
- fixes broken remote resource sync that could not find `RemoteResource` reference + `permissions` containers 

example of thredds service synched with a test daccs server

image

fix #401

### CODE REVIEW

File: CHANGES.rst [hunk 1]
```diff
@@ -11,6 +11,8 @@ Features / Changes
 ~~~~~~~~~~~~~~~~~~~~~
 * Explicitly require ``MAGPIE_ADMIN_USER`` and ``MAGPIE_ADMIN_PASSWORD`` to be updated through configuration and
   application restart. Update is forbidden through the API and UI.
+* Add UI loading animation while sync operation is in progress to indicate some user feedback that it was registered
+  and is running until completion as it can take a while to parse all remote resources (depends on amount and latency).
```
Comment (tlvu) [inline CHANGES.rst:15]: "it can take a while to parse all remote resources (depends on amount and latency)" this worries me a bit here.

How does Magpie "scan" for Thredds data structure?  Crawling via Thredds web UI?

In production we have a massive dataset on Thredds.  Last time we triggered the pavics crawler, it took 2 days to finish crawling Thredds !

What would happen if somehow Thredds and/or Mapie is restarted in the middle of the scan?

Does Magpie still operating "normally" performance wise during the scan?

Looks like Magpie also crawl the wpsoutput folder, that is also a source of massive content that is more or less useless.  Is there a way to exclude it from the scan (as a config option, not hardcoded).  Will surely help the scan to finish faster.

**Review by tlvu — DISMISSED** [review]
Approve the spirit of it, no idea for the code.

A little note about the scan/sync option.

File: CHANGES.rst (hunk 1 above)
Comment (fmigneault) [reply CHANGES.rst:15]: For the case of THREDDS, it uses `threddsclient.read_url` recursively for each children directories returned by each previous response. There is a `max_depth` parameter to limit this process. The idea is to go as far as needed to generate the structure required to apply permissions to avoid registering each resource by hand, but specific definitions can still be added manually after. If permissions are all applied to (at most) the displayed 4 levels, then no more pointless crawling should be done. For the moment, there is only `max_depth` (hardcoded) without any additional exclude, but both of these could be added to the thredds JSON config. 

Normally, one worker should be processing the sync, while others still can receive and answer to requests. 
If THREDDS stopped midway, I think the sync will fail because of error response. 
If Magpie is stops, it will simply not complete the scan.

**Review by dbyrns — COMMENTED** [review]
LGTM

File: CHANGES.rst (hunk 1 above)
Comment (tlvu) [reply CHANGES.rst:15]: Next time Thredds/Magpie comes back on line, will Magpie resume the scan?
